#theme = "catppuccin_mocha_transparent"
theme = "base16_default"

[editor]
color-modes = true
completion-replace = true
cursorcolumn = false
cursorline = true
line-number = "relative"
#rulers = [80]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.statusline]
left = ["mode", "spinner", "diagnostics", "workspace-diagnostics"]
center = [
    "file-encoding",
    "file-type",
    "separator",
    "file-name",
    "read-only-indicator",
    "separator",
    "spacer",
    "version-control",
    "file-modification-indicator",
]
right = [
    "position",
    "position-percentage",
]

#mode.normal = "NORMAL"
#mode.insert = "INSERT"
#mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "╎" 
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
"K" = "insert_newline"

# Move line up/down using A-k, A-j
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before"
]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before"
]
