theme = "term16_dark"

[editor]
color-modes = true
scrolloff = 9999
completion-replace = true
cursorcolumn = false
cursorline = true
line-number = "relative"
true-color = true
auto-format = true
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.indent-guides]
render = true
character = "╎"

[editor.soft-wrap]
enable = true
wrap-indicator = ''

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
"K" = "insert_newline"
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before",
]
C-g = [
":new",
":insert-output lazygit",
":buffer-close!",
":redraw",
":rla"
]
